name: Run Migrations

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  migrations:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Prepare environment
      run: |
        sed -i '/rosemary @ file:\/\/\/app/d' requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h 127.0.0.1 -uuvlhub_user -puvlhub_password --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Run Flask Migrations
      env:
        FLASK_ENV: production
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
        DATABASE_URL: mysql+pymysql://uvlhub_user:uvlhub_password@127.0.0.1:3306/uvlhubdb_test
      run: |
        flask db migrate -m "new_migration"
        flask db upgrade
