name: Run Migrations

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhubdb_root_password
          MYSQL_DATABASE: uvlhubdb
          MYSQL_USER: uvlhubdb_user
          MYSQL_PASSWORD: uvlhubdb_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Prepare environment
      run: |
        sed -i '/rosemary @ file:\/\/\/app/d' requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Grant Permissions to MySQL User
      run: |
        mysql -h127.0.0.1 -uroot -puvlhubdb_root_password -e "
        CREATE DATABASE IF NOT EXISTS uvlhubdb;
        GRANT ALL PRIVILEGES ON uvlhubdb.* TO 'uvlhubdb_user'@'%';
        CREATE DATABASE IF NOT EXISTS uvlhubdb_test;
        GRANT ALL PRIVILEGES ON uvlhubdb_test.* TO 'uvlhubdb_user'@'%';
        FLUSH PRIVILEGES;"

    - name: Debug MySQL Databases and Users
      run: |
        echo "Available Databases:"
        mysql -h127.0.0.1 -uroot -puvlhubdb_root_password -e "SHOW DATABASES;"
        echo "Users and Hosts:"
        mysql -h127.0.0.1 -uroot -puvlhubdb_root_password -e "SELECT user, host FROM mysql.user;"
        echo "Permissions for uvlhubdb_user:"
        mysql -h127.0.0.1 -uroot -puvlhubdb_root_password -e "SHOW GRANTS FOR 'uvlhubdb_user'@'%';"

    - name: Wait for MySQL to be Ready
      run: |
        for i in {1..10}; do
          if mysqladmin ping -h127.0.0.1 -uroot -puvlhubdb_root_password --silent; then
            echo "MySQL is up and running!"
            break
          fi
          echo "Waiting for MySQL to start..."
          sleep 5
        done

    - name: Run Migrations
      env:
        FLASK_ENV: development
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_DATABASE: uvlhubdb
        MARIADB_USER: uvlhubdb_user
        MARIADB_PASSWORD: uvlhubdb_password
        MARIADB_ROOT_PASSWORD: uvlhubdb_root_password
      run: |
        flask db migrate -m "new_migration"
        flask db upgrade