name: Run Migrations

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  migrations:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhubdb_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhubdb_user
          MYSQL_PASSWORD: uvlhubdb_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Prepare environment
      run: |
        sed -i '/rosemary @ file:\/\/\/app/d' requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h 127.0.0.1 -uuvlhubdb_user -puvlhubdb_password --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Execute MySQL Commands
      run: |
        # Eliminar bases de datos y usuario si existen
        mysql -h127.0.0.1 -uroot -puvlhubdb_root_password -e "
        DROP DATABASE IF EXISTS uvlhubdb;
        DROP DATABASE IF EXISTS uvlhubdb_test;
        DROP USER IF EXISTS 'uvlhubdb_user'@'%';
        CREATE DATABASE uvlhubdb;
        CREATE DATABASE uvlhubdb_test;
        CREATE USER 'uvlhubdb_user'@'%' IDENTIFIED BY 'uvlhubdb_password';
        GRANT ALL PRIVILEGES ON uvlhubdb.* TO 'uvlhubdb_user'@'%';
        GRANT ALL PRIVILEGES ON uvlhubdb_test.* TO 'uvlhubdb_user'@'%';
        FLUSH PRIVILEGES;"

    - name: Debug MySQL Setup
      run: |
        mysql -h127.0.0.1 -uroot -puvlhubdb_root_password -e "
        SHOW DATABASES;
        SELECT user, host FROM mysql.user;"

    - name: Run Flask Migrations
      env:
        FLASK_APP_NAME: "UVLHUB.IO(dev)"
        FLASK_ENV: development
        DOMAIN: localhost
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_DATABASE: uvlhubdb
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhubdb_user
        MARIADB_PASSWORD: uvlhubdb_password
        MARIADB_ROOT_PASSWORD: uvlhubdb_root_password
        WORKING_DIR: ""
        DATABASE_URL: mysql+pymysql://uvlhubdb_user:uvlhubdb_password@127.0.0.1:3306/uvlhubdb_test
      run: |
        flask db upgrade  # Applies the migrations
        flask db migrate -m "new_migration"  # Creates new migrations
        flask db upgrade  # Applies any new migrations after migration generation

    - name: Commit migration file
      run: |
        # Configurar usuario de Git para hacer commit con el token de GitHub
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Añadir los archivos de migración generados
        git add migrations/versions/*.py

        # Realizar el commit de los archivos de migración
        git commit -m "Add new migration"

        # Hacer push de los cambios al repositorio utilizando el GITHUB_TOKEN
        git push origin $GITHUB_REF
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
